[{
	"Id": "0",
	"Name": "主页",
	"Type": 1,
	"URL": "javascript:;",
	"ParentId": null,
	"SubMenu": []
}, {
	"Id": "1",
	"Name": "身份认证中心",
	"URL": "javascript:;",
	"ParentId": null,
	"Type": 1,
	"SubMenu": [{
		"Id": "10",
		"Name": "设备申请",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}, {
		"Id": "11",
		"Name": "设备锁定",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}, {
		"Id": "12",
		"Name": "人员锁定",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}, {
		"Id": "13",
		"Name": "应用程序锁定",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}, {
		"Id": "14",
		"Name": "应用程序更新",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}, {
		"Id": "15",
		"Name": "人员设备",
		"URL": "javascript:;",
		"ParentId": "1",
		"Type": 3,
		"SubMenu": null
	}]
}, {
	"Id": "2",
	"Name": "工作中心",
	"URL": "javascript:;",
	"ParentId": null,
	"Type": 1,
	"SubMenu": [{
		"Id": "20",
		"Name": "文档库",
		"URL": "javascript:;",
		"ParentId": "2",
		"Type": 2,
		"SubMenu": [{
			"Id": "210",
			"Name": "文档库管理",
			"URL": "javascript:;",
			"ParentId": "20",
			"Type": 3,
			"SubMenu": null
		}, {
			"Id": "220",
			"Name": "信息点管理",
			"URL": "javascript:;",
			"ParentId": "20",
			"Type": 3,
			"SubMenu": null
		}, {
			"Id": "230",
			"Name": "文档审核",
			"URL": "javascript:;",
			"ParentId": "20",
			"Type": 3,
			"SubMenu": null
		}]
	}, {
		"Id": "21",
		"Name": "工作中心配置",
		"URL": "javascript:;",
		"ParentId": "2",
		"Type": 3,
		"SubMenu": null
	}]
}]